# Site settings
title: Max Jendruk – Business Card
email: contact@jendruk.com
description: > # this means to ignore newlines until "baseurl:"
  Online Business Card of Max Jendruk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://max.jendruk.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
